spring:
  resources:
    static-locations:
    - file:/data/html
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cg?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
logging:
  config: classpath:logger/app-dev.xml
#app config
app:
  devMode: true
  provider:
    host: http://beta.api.nuls.io/
  contract:
    address: "NseBjBn7JTUF94zCY6U4jkkLZupwBwnW"
    refund-address: "Nsdv1Hbu4TokdgbXreypXmVttYKdPT1g"
    refund-password: "nuls123456"