spring:
  resources:
    static-locations:
    - file:/data/html
  datasource:
    url: jdbc:mysql://127.0.0.1:3136/vote_new?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: vote
    password: Nuls123456
    driver-class-name: com.mysql.jdbc.Driver
logging:
  config: classpath:logger/app-prod.xml
#app config
app:
  devMode: false
  provider:
    host: http://127.0.0.1:6001
  contract:
    address: "NseQih5xZa6vAWsL6uY5drozyW4tqzQx"
    refund-address: "Nse6NAJnhSmGqvx3prJf3yVWAvMY6zd8"
    refund-password: "1234qwer"